Kick-Off
wolox-training/fec-express-js pull request #1
Opened 2018-10-23 13:11 UTC by fede1608

# Summary

- Kick-Off express.js application

# Trello Card
[https://trello.com/c/RFx3r32b/1-kick-off](https://trello.com/c/RFx3r32b/1-kick-off)

2018-10-23 18:15 UTC, mpizzagalli requested changes
Two little comments

2018-10-23 18:15 UTC, mpizzagalli commented on .nvmrc
> +lts/*
let's use `lts/carbon`

2018-10-23 18:15 UTC, mpizzagalli commented on package.json
> +    "npm": "2.14.2"
check which version you are actually using and change it here, to avoid future problems with heroku

2018-10-23 19:12 UTC, fede1608 commented
Fixed

2018-10-24 14:11 UTC, mpizzagalli approved these changes
Remember to assign me once I have to look at the PR again, so I get a github notification.

2018-10-25 15:42 UTC, merged